### ISSUE TITLE
쿼리 무효화 invalidateQueries 설명 관련

### ISSUE THREAD

**Issue by stakbucks** [ssi02014/react-query-tutorial#20]
안녕하세요.
너무 좋은 자료 감사합니다. 도움 많이 됐고 v5 관련 업데이트도 기대하고 있습니다. 

공식문서와 함께 읽으며 공부하던 도중에 [쿼리 무효화](https://github.com/ssi02014/react-query-tutorial#%EC%BF%BC%EB%A6%AC-%EB%AC%B4%ED%9A%A8%ED%99%94) 부분에서 의문스러운 부분이 있어서 이슈 남겨봅니다.

무효화 하려는 키가 여러 개인 경우에 대한 설명이 다음과 같이 나와있는데요,
> - 만약 무효화 하려는 키가 여러 개라면 아래 예제와 같이 다음과 같이 배열로 보내주면 된다.
`queryClient.invalidateQueries(["super-heroes", "posts", "comment"]);`

하지만, 공식문서에 따르면 invalidateQueries와 관련하여, 여러 개의 쿼리를 prefix를 이용해서 무효화 시킬 수 있다고 나옵니다.
즉, `queryClient.invalidateQueries(["super-heroes"]);` 는 `["super-heroes"]`가 prefix인 쿼리키를 갖는 모든 쿼리를 무효화 시키고, `queryClient.invalidateQueries(["super-heroes", "posts", "comment"])`는 오히려 여러 개의 키를 무효화 시키는 것이 아니라, `["super-heroes", "posts", "comment"]`라는 정확한 키 하나에 해당하는 쿼리를 무효화 시킨다고 보는 게 맞는 거 같습니다.  [공식문서 Query Matching with invalidateQueries ](https://tanstack.com/query/v4/docs/react/guides/query-invalidation#query-matching-with-invalidatequeries)

만약에 독립적인 여러개의 쿼리키를 무효화 시키고 싶다면 
```
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

const useAddSuperHeroData = () => {
  const queryClient = useQueryClient();
  return useMutation(addSuperHero, {
    onSuccess(data) {
      queryClient.invalidateQueries(["super-heroes"]);
      queryClient.invalidateQueries(["posts"]);
      queryClient.invalidateQueries(["comment"]); 
    },
    onError(err) {
      console.log(err);
    },
  });
};
```
위와 같이 `invalidateQueries`를 여러 번 작성하는 것이 더 적절할 것 같습니다. 

실제로 아래는 공식문서에 사용된  mutation시 `onSuccess` 콜백에서 여러개의 쿼리키를 무효화 시키는 예제 코드입니다.
[공식문서 Invalidations from Mutations](https://tanstack.com/query/v4/docs/react/guides/invalidations-from-mutations)
```
import { useMutation, useQueryClient } from '@tanstack/react-query'

const queryClient = useQueryClient()

// When this mutation succeeds, invalidate any queries with the `todos` or `reminders` query key
const mutation = useMutation({
  mutationFn: addTodo,
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: ['todos'] })
    queryClient.invalidateQueries({ queryKey: ['reminders'] })
  },
})
```
혹시 제가 문서를 잘못 이해하고 있었다면 말씀해주세요.
감사합니다!

**Comment by ssi02014** [comment]
@stakbucks 이슈 등록 감사합니다 😄 
해당 내용은 제가 작성 당시에 이해도가 낮았던 것 같습니다.
괜찮으시다면 해당 예제에대해서 수정 작업 후 PR 등록해주실 수 있나요? 
놓친 부분에대해서 이슈를 남겨주셔서 다시 한번 감사드립니다.

**Comment by stakbucks** [comment]
@ssi02014  
빠른 확인 감사합니다. 너무 좋은 저장소라 기여할 수 있다면 좋을 거 같습니다.
발견한 오타도 몇가지 있어서, 그 부분까지 수정까지해서 이번 주 내로 PR 올려보겠습니다!

**Comment by ssi02014** [comment]
@stakbucks 
네 감사합니다! 😄  아래 내용 및 오타 수정 작업 감사드립니다! 

>만약 무효화 하려는 키가 여러 개라면 아래 예제와 같이 다음과 같이 배열로 보내주면 된다.
queryClient.invalidateQueries(["super-heroes", "posts", "comment"]);

아 그리고 현재 v5 문서 업데이트를 위해 `README.md(v5 준비 예정)`, `README.v4.md` 2가지 파일이 존재한 상태입니다. 
불편하시겠지만 두 가지 모두 수정해주시면 감사드립니다 🙇‍♂️

**Comment by stakbucks** [comment]
@ssi02014
네 알겠습니다 😀
