### ISSUE TITLE
목차에 적힌 cancelQueries 내용

### ISSUE THREAD

**Issue by j2e4** [ssi02014/react-query-tutorial#25]
안녕하세요!

> 쿼리 수동 무효화 cancelQueries

목차 24번에 해당하는 위 내용에서 `무효화`를 `취소`로 변경하는 게 더 정확한 의미를 가진다고 생각해 의견 드립니다.

**Comment by ssi02014** [comment]
의견 감사합니다 👍
7825f71 해당 커밋에서 수정되었습니다 🙏
