### ISSUE TITLE
캐싱 라이프 사이클 설명 보완

### ISSUE THREAD

**Issue by parkm2ngyu00** [ssi02014/react-query-tutorial#35]
안녕하세요, 문서 잘 보고 있습니다. 그런데 보다보니 조금 표현이 불명확한 문장이 있는것 같아 알려드리고자 합니다.

캐싱 라이프 사이클의 6번 문장   
`6. 만일, gcTime 지나기 전이고, A 쿼리 인스턴스 fresh한 상태라면 새롭게 mount되면 캐시 데이터를 보여준다.`
이 문장의 설명이 조금 헷갈리는 부분이 있다고 생각합니다.   
만일, gcTime이 지나기 전이고, A 쿼리 인스턴스가 stale한 상태라면 다시 mount되면 우선 캐시 데이터를 보여준다.
이후, 백그라운드에서 자동으로 refetch를 실행한다. 새 데이터로 캐시 데이터가 변경되고, 이를 반영해 사용자에게 보여준다.   
위 설명이 더 명확할 것 같습니다.

감사합니다.

**Comment by ssi02014** [comment]
의견 감사합니다 해당 부분은 조금 더 검토 후에 수정이 필요하면 수정하도록 하겠습니다.
