### ISSUE TITLE
데이터의 종속성 (Data Dependency)

### ISSUE THREAD

**Issue by advanced-rising** [ssi02014/react-query-tutorial#6]
useCallback 대신해서 useQuery에 들어오는 [ ] 종속성 배열은 똑같은 기능을 하기에 더이상 Callback을 사용하지 않고 사용할 수 있다고 합니다.

혹시 적어져 있나요 ? 
찾다보니.. 이러하네요 ..

**Comment by ssi02014** [comment]
어떤 것을 말씀하시는거쥬..!?😮
